name: Ignite Your Intuition In 21 Days
favicon: null
layout_spectrum: 0.09308672253973782
typography_spectrum: 0.07532018166966736
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.3004970094189048
  lightness: 0.899138098815456
  saturation: 0.7792860253248364
  rhythmicContrast: 0.06367368600331247
purpose: []
