name: Ignite Your Intuition In 21 Days
favicon: null
layout_spectrum: 0.49771
typography_spectrum: 0.07532018166966736
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0a0502'
    - '#9f9f9f'
    - '#b96f3e'
    - '#7e3312'
  brandStrength: 0.3004970094189048
  lightness: 0.899138098815456
  saturation: 0.7792860253248364
  rhythmicContrast: 0.06367368600331247
purpose: []
